# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/client" # Location of the client's package.json
    schedule:
      interval: "daily" # In this daily configuration, we allow GitHub to check if there are some more versions for our packages, even if it is not for security reasons.
  - package-ecosystem: "npm"
    directory: "/server" # Location of the server's package.json
    schedule:
      interval: "daily"
  - package-ecosystem: "docker" # This tells Dependabot to look for updates to Docker images. Docker images are the container images specified in Dockerfiles.
    directory: "/" # The current Location of Dockerfile(s)
    schedule:
      interval: "daily"
