version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
  server:
    build: .
    command: npm start
    volumes:
      - .:/usr/src/git-actions-practice
    ports:
      - "5000:5000"
    depends_on:
      - mongo
  client:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    volumes:
      - .:/usr/src/git-actions-practice
    ports:
      - "5173:5173"
    depends_on:
      - server
