- name: Create a nginx server with site
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - group_vars/env
  vars:
      ansible_python_interpreter: /usr/bin/python3

  tasks:
  - name: create VPC
    amazon.aws.ec2_vpc_net:
      name: "{{ vpc_name }}"
      cidr_block: "{{ network }}"
      region: "{{ aws_region }}"
      state: present
      dns_hostnames: yes
      dns_support: yes
      multi_ok: no
      tags:
        Name: "{{ vpc_name }}"
    register: vpc

  # - debug:
  #     var: vpc

  - name: Add VPC definition to vars file
    lineinfile:
      path: group_vars/env
      regexp: 'vpc_id: '
      line: 'vpc_id: {{ vpc.vpc.id }}'
      state: present
      create: True

  - name: associate subnet to the VPC
    amazon.aws.ec2_vpc_subnet:
      state: present
      vpc_id: "{{ vpc.vpc.id }}"
      region: "{{ aws_region }}"
      cidr: "{{ subnet_cidr }}"
      map_public: yes
      az: "{{ subnet }}"
      resource_tags:
        Name: "{{ vpc_name }}"
      wait: yes
    register: subnet

  - name: Add subnet definition to vars file
    ansible.builtin.lineinfile:
      path: group_vars/colman.env
      regexp: 'subnet_id: '
      line: 'subnet_id: {{ subnet.subnet.id }}'
      state: present
      create: True  