name: Node.js CD Pipeline

on:
  workflow_run:
    workflows: [ "Node.js CI Pipeline" ]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Run a script to deploy the application
        run: |
          #          cd /home/ubuntu
          #          sudo ./deploy_application.sh
               sudo /home/ubuntu/deploy_application.sh