name: Node.js CD Pipeline

on:
  workflow_run:
    workflows: [ "Node.js CI Pipeline" ]
    types:
      - completed

jobs:
  deploy: # Hello world
    runs-on: self-hosted

    steps:
      - name: Log in to Docker Hub
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Pull Docker images
        run: |
          docker pull avivnat13/devops_project-client:latest
          docker pull avivnat13/devops_project-server:latest
          docker pull mongo:6-jammy

      - name: Start Docker containers
        run: |
          sudo ./deploy_application.sh
#          sudo docker network create node-network || true
#          sudo docker run -d --name mongodb --network=node-network -p 27017:27017 -v dbdata6:/data/db mongo:6-jammy
#          sudo docker run -d --name api --network=node-network -p 5000:5000 \
#            -e MONGO_URI=$MONGO_URI \
#            -e JWT_SECRET=$JWT_SECRET \
#            -e JWT_REFRESH_SECRET=$JWT_REFRESH_SECRET \
#            -e JWT_EXPIRATION=$JWT_EXPIRATION \
#            -e GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID \
#            avivnat13/devops_project-server:latest
#          sudo docker run -d --name client --network=node-network -p 5173:5173 avivnat13/devops_project-client:latest