name: Node.js CD Pipeline
# This CD pipeline triggered when the CI completely done.
on:
  workflow_run:
    workflows: [ "Node.js CI Pipeline" ]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script_stop: true
          script: |
            docker stop api client || true
            docker rm api client || true
            docker rmi avivnat13/devops_project-client:latest || true
            docker rmi avivnat13/devops_project-server:latest || true
            docker pull avivnat13/devops_project-client:latest
            docker pull avivnat13/devops_project-server:latest
            docker run -d --name api --network=node-network -p 5000:5000 \
            -e MONGO_URI=mongodb://mongodb:27017/mydatabase \
            -e JWT_SECRET="mysecret" \
            -e JWT_REFRESH_SECRET="myrefreshsecret" \
            -e JWT_EXPIRATION="1h" \
            -e GOOGLE_CLIENT_ID="12312312312312312" \
            avivnat13/devops_project-server:latest
            docker run -d --name client --network=node-network -p 5173:5173 avivnat13/devops_project-client:latest