name: Node.js CD Pipeline
# This CD pipeline triggered when the CI completely done.
on:
  workflow_run:
    workflows: [ "Node.js CI Pipeline" ]
    types:
      - completed

# jobs:
#   deploy:
#     runs-on: self-hosted # Define the EC2 machine as a self-hosted runner that waits for tasks.
#     # When it is triggered, it runs the commands below.
#     steps:
#       - name: Run a script to deploy the application
#         run: |
#           sudo /home/ubuntu/deploy_application.sh

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
            python-version: 3.8

      - name: Install SSH Client
        run: sudo apt-get install openssh-client

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      - name: create env variable
        run: export GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}

      - name: Deploy Application
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.PRIVATE_KEY }} ubuntu@${{ secrets.EC2_PUBLIC_IP }} 'bash -s' < ~/deploy_application.sh